name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Download dependencies
      run: sudo apt-get install -y libx11-xcb-dev libxcb-randr0-dev libxcb-xinerama0-dev
    - name: Build
      run: make CFLAGS='-DWITH_XINERAMA=1'
    - name: Check
      run: ./lemonbar -h
